Source/MotelSystem/src/java/model/Message.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import java.util.Date;

/**
 *
 * @author Admin
 */
public class Message {
    private int MessageID;
    private int From;
    private int To;
    private String Content;
    private Date CreateAt;

    public Message() {
    }

    public Message(int MessageID, int From, int To, String Content, Date CreateAt) {
        this.MessageID = MessageID;
        this.From = From;
        this.To = To;
        this.Content = Content;
        this.CreateAt = CreateAt;
    }

    public Message(int From, int To, String Content, Date CreateAt) {
        this.From = From;
        this.To = To;
        this.Content = Content;
        this.CreateAt = CreateAt;
    }

    public Message(int From, int To, String Content) {
        this.From = From;
        this.To = To;
        this.Content = Content;
    }

    
    public int getMessageID() {
        return MessageID;
    }

    public void setMessageID(int MessageID) {
        this.MessageID = MessageID;
    }

    public int getFrom() {
        return From;
    }

    public void setFrom(int From) {
        this.From = From;
    }

    public int getTo() {
        return To;
    }

    public void setTo(int To) {
        this.To = To;
    }

    public String getContent() {
        return Content;
    }

    public void setContent(String Content) {
        this.Content = Content;
    }

    public Date getCreateAt() {
        return CreateAt;
    }

    public void setCreateAt(Date CreateAt) {
        this.CreateAt = CreateAt;
    }
    
    
}

Source/MotelSystem/src/java/controller/customer/ChooseRoleController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller.customer;

import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 *
 * @author coder
 */
public class ChooseRoleController extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try (PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet ChooseRoleController</title>");            
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet ChooseRoleController at " + request.getContextPath() + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
//        processRequest(request, response);
        request.getRequestDispatcher("/page/chooserole.jsp").forward(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

Source/MotelSystem/src/java/controller/customer/LogoutController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller.customer;

import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 *
 * @author coder
 */
public class LogoutController extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        request.getSession().setAttribute("accountAllInfor", null);
//        response.getWriter().println("logged out!");
        request.getRequestDispatcher("home").forward(request, response);
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

Source/MotelSystem/src/java/controller/customer/PostDetailCustomerController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller.customer;

import dal.MotelDAO;
import dal.PostDAO;
import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 *
 * @author royal
 */
@WebServlet(name = "PostDetailCustomerController", urlPatterns = {"/customer/PostDetailCustomer"})
public class PostDetailCustomerController extends BaseAuthenticationControllerCustomer {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try (PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet PostDetailCustomerController</title>");            
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet PostDetailCustomerController at " + request.getContextPath() + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void processGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
         PostDAO dao = new PostDAO();
        int postID = Integer.parseInt(request.getParameter("postID"));
        request.setAttribute("post", dao.getPostDetail(postID));
        request.getRequestDispatcher("/page/customer/post-detail-customer.jsp").forward(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void processPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

Source/MotelSystem/src/java/controller/customer/SignUpController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller.customer;

import commnon.HashPassword;
import dal.AccountDAO;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import model.Account;
import model.Profile;

/**
 *
 * @author Admin
 */
public class SignUpController extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try (PrintWriter out = response.getWriter()) {

        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
//        processRequest(request, response);
        request.getRequestDispatcher("../page/SignUpAccount.jsp").forward(request, response);
        System.out.println("test dang ky");
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
//        processRequest(request, response);
        request.setCharacterEncoding("UTF-8");
        response.setCharacterEncoding("UTF-8");
        response.setContentType("text/html; charset=UTF-8");
        AccountDAO AD = new AccountDAO();
        HashPassword hashPass = new HashPassword();
        String username = request.getParameter("user_name");
        boolean existUsername = AD.CheckUsernameExist(username);  
        String email = request.getParameter("email");
        boolean existEmail = AD.CheckEmailExist(email);
        if(existUsername || existEmail){
            String error = "Tên tài khoản hoặc email đã được sử dụng";
            request.setAttribute("error", error);
            request.getRequestDispatcher("../page/SignUpAccount.jsp").forward(request, response);
            return;
        }
        String password = request.getParameter("user_password");
        String fullname = request.getParameter("name");
        String phone = request.getParameter("contact_no");
        String address = request.getParameter("address");        
        String date = request.getParameter("DOB");
        SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
        Date dob = null;
        try {
            dob = dt.parse(date);
        } catch (ParseException ex) {
            Logger.getLogger(SignUpController.class.getName()).log(Level.SEVERE, null, ex);
        }
        String gender = request.getParameter("gender");
        String imageProfile = request.getParameter("image");
        Account account = new Account(username, hashPass.encryptPassword(password));
        boolean createstatus = AD.CreateAccount(account);
        if (!createstatus) {
            String error = "Tạo tài khoản không thành công";
            request.setAttribute("error", error);
            request.getRequestDispatcher("../page/SignUpAccount.jsp").forward(request, response);
        } else {
            Account getA = AD.GetAccountByUserNameAndPass(account);
            Profile profile = new Profile(getA.getAccountID(), fullname, phone, address, email, dob, gender, imageProfile);
            boolean profilestatus = AD.CreateProfile(profile);
            boolean rolestatus = AD.CreateRoleOfAccount(getA.getAccountID());
            if(profilestatus && rolestatus){
                response.sendRedirect("login");
            }else{
                String error = "Tạo tài khoản không thành công";
                request.setAttribute("error", error);
                request.getRequestDispatcher("../page/SignUpAccount.jsp").forward(request, response);
            }
        }
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

Source/MotelSystem/web/page/customer/booking-detail.jsp
<%-- 
    Document   : homepage-normal
    Created on : May 14, 2022, 1:43:58 AM
    Author     : royal
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<!DOCTYPE html>
<html lang="en" style="overflow: auto;">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Chi tiết đặt phòng</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <!-- Favicon-->
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="<%= request.getContextPath()%>/css/normal-homepage.css" rel="stylesheet" />

        <style>
            i{
                color: #8080CC;
            }
        </style>
    </head>
    <body>
        <!-- Navigation-->
        <!--        <nav class="navbar navbar-expand-lg navbar-light bg-light" style="display: none">
                    <div class="container px-4 px-lg-5">
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                                <li class="nav-item"><a class="nav-link active" aria-current="page" href="<%= request.getContextPath()%>/home">Trang chủ</a></li>
        
                            </ul>
                            <form class="d-flex" action="chooserole">
                                <input type="submit" class="btn btn-dark" value="Đăng nhập">
                            </form>
                        </div>
                    </div>
                </nav>-->


        <jsp:include page="nav-home-customer.jsp">
            <jsp:param name="nav" value="ManageBooking"></jsp:param>
        </jsp:include>

        <!-- Header-->
        <!-- Section-->

        <section style="padding-bottom: 5em;">
            <div class="container mt-5" style="border: 2px solid #8080CC;padding-top: 20px; border-radius: 10px;box-shadow: rgba(50, 50, 93, 0.25) 0px 50px 100px -20px, rgba(0, 0, 0, 0.3) 0px 30px 60px -30px;">
                <div class="row px-4" style="padding-bottom: 20px;padding-top: 20px">
                    <div class="col px-4" style="border-right: 2px solid #8080CC">
                        <div style="width: 100%;height: 80%;position: relative;padding-right: 0px;">
                            <c:forEach var="profile" items="${bookingDetails.listProfile}" varStatus="theCount">
                                <p><b><i>Người Thuê: ${theCount.count}</i></b></p>

                                <div class="row">
                                    <div class="col-4">
                                        <img src="data:image/jpg;base64,${profile.imageProfile}" style="width:100%;height: auto;"><br>
                                    </div>
                                    <div class="col-8">
                                        <b><i>Họ Tên:</i> ${profile.fullName}</b> <b></b> <br>
                                        <b><i>Số Điện Thoại:</i> ${profile.phone}</b> <b></b> <br>
                                        <b><i>Địa Chỉ:</i> ${profile.address}</b> <b></b> <br>
                                        <fmt:parseDate pattern="yyyy-MM-dd" value="${profile.dOB}" var="parsedDOB" />
                                        <b><i>Ngày Sinh:</i> <fmt:formatDate value="${parsedDOB}" pattern="dd/MM/yyyy" /></b> <b></b> <br>
                                        <b><i>Giới Tính:</i> ${profile.gender}</b> <b></b> <br>
                                    </div>
                                </div>
                                <br>
                            </c:forEach>
                        </div>
                    </div>
                    <div class="col" style="padding-left:50px">
                        <div class="row" style="margin-top: 30px">
                            <div class="col-3">
                                <p><b><i>Tên Trọ:</i></b></p>
                            </div>
                            <div class="col-9">
                                <h4>${bookingDetails.motelName}</h4>
                            </div>
                        </div>
                        <div class="row" style="margin-top: 30px">
                            <div class="col-3">
                                <p><b><i>Tên Phòng:</i></b></p>
                            </div>
                            <div class="col-9">
                                <h5>${bookingDetails.roomName}</h5>
                            </div>
                        </div>
                        <div class="row" style="margin-top: 30px">
                            <div class="col-3">
                                <p><b><i>Ngày Bắt Đầu</i></b></p>
                            </div>
                            <div class="col-9">
                                <fmt:parseDate pattern="yyyy-MM-dd" value="${bookingDetails.startAt}" var="parsedDateS" />
                                <h5><fmt:formatDate value="${parsedDateS}" pattern="dd/MM/yyyy" /></h5>
                            </div>
                        </div>
                        <div class="row" style="margin-top: 30px">
                            <div class="col-3">
                                <p><b><i>Ngày Kết Thúc</i></b></p>
                            </div>
                            <div class="col-9">
                                <fmt:parseDate pattern="yyyy-MM-dd" value="${bookingDetails.endAt}" var="parsedDateE" />
                                <h5><fmt:formatDate value="${parsedDateE}" pattern="dd/MM/yyyy" /></h5>
                            </div>
                        </div>
                        <div class="row" style="margin-top: 30px">
                            <div class="col-3">
                                <p><b><i>Giá:</i></b></p>
                            </div>
                            <div class="col-9">
                                <fmt:setLocale value="vi-VN"/>

                                <h5>
                                    <fmt:formatNumber type = "currency" value = "${bookingDetails.price}" />
                                </h5>
                            </div>
                        </div>
                        <div class="row" style="margin-top: 30px">
                            <div class="col-12">
                                <p><b><i>Các Dịch Vụ Sử Dụng</i></b></p>
                            </div>
                            <div class="col-9">
                                <table border="1">
                                    <tbody >
                                        <tr style="border-width: 2px; width: 200px;">
                                            <td style="border-width: 2px; width: 200px;">Tên Dịch Vụ</td>
                                            <td style="border-width: 2px; width: 200px;">Giá</td>
                                        </tr>
                                        <c:forEach var="services" items="${bookingDetails.listServices}">
                                            <tr style="border-width: 2px; width: 200px;">
                                                <td style="border-width: 2px; width: 200px;">${services.servicesName}</td>
                                                <td style="border-width: 2px; width: 200px;">${services.price}</td>
                                            </tr>
                                        </c:forEach>
                                    </tbody>
                                </table>


                            </div>
                        </div>
                    </div>
                </div><br/>
            </div>
        </section>
        <!-- Footer-->
        <jsp:include page="../footer.html"/>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

    </body>


</html>

Source/MotelSystem/web/page/customer/requestDetail.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Chi tiết yêu cầu phòng</title>
        <link rel="stylesheet" href="../css/host/updateRoom.css">
        <link href="../../css/host/updateRoom.css" rel="stylesheet" type="text/css"/>
        <script language="javascript" src="../js/host/updateRoom.js"></script>
    </head>
    <body>
            <form name="myForm" id="myForm" class="form" action="updaterequest" method="post">
            <h2>Chi Tiết Thông Tin Yêu Cầu</h2>
            <c:set value="${requestScope.requestOfRoomById}" var="request"/>
            <input type="hidden" value="${request.requestID}" name="idRequest">
            <p type="Tên Trọ:">
                
                <input name="roomName" value="${request.motelName}" readonly="">
            </p>
            <p type="Tên Phòng:">
                
                <input name="roomName" value="${request.roomName}" readonly="">
            </p>
            <p type="Nội dung yêu cầu">
                <input name="content" value="${request.content}" readonly="">
            </p>
            <p type="Ngày tạo">
                <input name="numberCurrent" value="<fmt:formatDate value="${request.createAt}" pattern="dd/MM/yyyy" />" readonly="">
            </p>
            <p type="Ghi chú từ trọ">
                <input name="notefromRoom" value="${request.noteRequestOfRoom}" readonly="">
            </p>
            <p type="Ghi chú từ chủ trọ">
                <input name="note" value="${request.noteRequestOfHost}">
            </p>
            <p type="Trạng thái">
                <c:if test="${request.status == '0'}">
                    <input value="Chưa xem"readonly="">
                </c:if>
                <c:if test="${request.status eq 'do'}">
                    <input value="Đang hoàn thành" readonly="">
                </c:if>
                <c:if test="${request.status eq 'done'}">
                    <input value="Đã hoàn thành" readonly="">
                </c:if> 
                <c:if test="${request.status eq 'reject'}">
                    <input value="Hủy yêu cầu" readonly="">
                </c:if> 
                <c:if test="${request.status eq 'seen'}">
                    <input value="Đã xem" readonly="">
                </c:if> 

            </p>
            <a href="../customer/request" style="display: flex;float: left;">Quay lại danh sách yêu cầu</a>
            </form>
    </body>
</html>

Source/MotelSystem/web/page/customer/updateRequest.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Cập nhật yêu cầu phòng</title>
        <link rel="stylesheet" href="../css/host/updateRoom.css">
        <link href="../../css/host/updateRoom.css" rel="stylesheet" type="text/css"/>
        <script language="javascript" src="../js/host/updateRoom.js"></script>
    </head>
    <body>
        <form name="myForm" id="myForm" class="form" action="updaterequest" method="post">
            <h2>Cập Nhật Thông Tin Yêu Cầu</h2>
            <c:set value="${requestScope.requestOfRoomById}" var="request"/>
            <input type="hidden" value="${request.requestID}" name="idRequest">
            <p type="Tên Trọ:">
                
                <input name="roomName" value="${request.motelName}" readonly="">
            </p>
            <p type="Tên Phòng:">
                
                <input name="roomName" value="${request.roomName}" readonly="">
            </p>
            <p type="Nội dung yêu cầu">
                <input name="content" value="${request.content}">
            </p>
            <p type="Ngày tạo">
                <input name="numberCurrent" value="<fmt:formatDate value="${request.createAt}" pattern="dd/MM/yyyy" />" readonly="">
            </p>
            <p type="Ghi chú từ trọ">
                <input name="note" value="${request.noteRequestOfRoom}">
            </p>
            <p type="Ghi chú từ chủ trọ">
                <input name="notefromHost" value="${request.noteRequestOfHost}" readonly="">
            </p>
            <p type="Trạng thái">
                <c:if test="${request.status == '0'}">
                    <input value="Chưa xem"readonly="">
                </c:if>
                <c:if test="${request.status eq 'do'}">
                    <input value="Đang hoàn thành" readonly="">
                </c:if>
                <c:if test="${request.status eq 'done'}">
                    <input value="Đã hoàn thành" readonly="">
                </c:if> 
                <c:if test="${request.status eq 'reject'}">
                    <input value="Hủy yêu cầu" readonly="">
                </c:if> 
                <c:if test="${request.status eq 'seen'}">
                    <input value="Đã xem" readonly="">
                </c:if> 

            </p>
            <a href="../customer/request" style="display: flex;float: left;">Quay lại danh sách yêu cầu</a>
            <input value="Cập nhật" type="submit"> 
            </form>
    </body>
</html>